# Generated by Django 4.1.6 on 2023-05-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencia',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
