# Generated by Django 4.1.6 on 2023-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='producto',
            new_name='productos',
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
