# Generated by Django 4.1.6 on 2023-05-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuariosLicoreria',
        ),
    ]
